# Generated by Django 6.0.4 on 2026-04-22 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('mr', 'Monsieur'), ('mme', 'Madame'), ('x', 'Autre')], default='x', max_length=10)),
                ('type', models.CharField(choices=[('outsider', 'Exterieur'), ('enfant', 'Enfant'), ('parent', 'Parent'), ('encadrant', 'Encadrant'), ('directeur', 'Directeur')], default='x', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
