# Generated by Django 4.2.11 on 2026-04-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('outsider', 'Exterieur'), ('enfant', 'Enfant'), ('parent', 'Parent'), ('encadrant', 'Encadrant'), ('directeur', 'Directeur')], default='outsider', max_length=10),
        ),
    ]
