# Generated by Django 4.2.11 on 2026-04-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_attempts_profile_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(choices=[('aile-ouest', 'Aile Ouest'), ('aile-est', 'Aile Est'), ('salle-principale', 'Salle principale'), ('exterieur', 'Extérieur')], max_length=50)),
                ('target', models.CharField(choices=[('parent', 'Parent'), ('enfant-0-5', 'Enfant < 5 ans'), ('enfant-5-10', 'Enfant 5–10 ans'), ('encadrant', 'Encadrant')], max_length=50)),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('divertissement', 'Divertissement'), ('nourriture', 'Nourriture'), ('activite', 'Activité'), ('cours', 'Cours')], max_length=50)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
