# Generated by Django 4.2.11 on 2026-04-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(choices=[('cuisine', 'Cuisine'), ('salle-principale', 'Salle principale'), ('dortoir', 'Dortoir'), ('toutes-ailes', 'Toutes les ailes')], max_length=50)),
                ('target', models.CharField(choices=[('enfant', 'Enfant'), ('encadrant', 'Encadrant')], max_length=50)),
                ('category', models.CharField(choices=[('alimentation', 'Alimentation'), ('divertissement', 'Divertissement'), ('confort', 'Confort')], max_length=50)),
                ('status', models.CharField(choices=[('allume', 'Allumé'), ('eteint', 'Éteint'), ('veille', 'En veille')], max_length=20)),
            ],
        ),
    ]
